### ISSUE TITLE
Create Build task to run on netlify deploy

### ISSUE THREAD

**Issue by w3cj** [CodingGarden/flags#8]
- [ ] Generate metadata.json
- [ ] Generate png images
- [ ] Generate CSS library...
- [ ] ETC...

**Comment by Joehoel** [comment]
I think you can add this to you `netlify.toml`

```toml
[build]
  command = "node scripts/generateScaledPNG.mjs && node scripts/generateMetadataJSON.mjs" 
```

To make it cleaner you can create a single file that runs all the scripts and call that from the build command.

Disclaimer: Have not tested this

Docs for `netlify.toml` https://docs.netlify.com/configure-builds/file-based-configuration/
